

info = {'name': 'Alex', 'family': 'V-----n', 'age': 35}
print(info)
phone = {}
print(phone)
phone['model'] = 'Mi11-lite'
print(phone)
phone['type'] = 'smartphone'
print(phone)
phone['data'] = 2021
print(phone)
phone['diagonal'] = 6.55
print(phone)
phone['company'] = 'XIAOMI'
print(phone)
phone['RAMM'] = '6Gb'
print(phone)


string = '''Those who are esteemed umpires of taste are often persons who have acquired some knowledge of admired pictures or sculptures, and have an inclination for whatever is elegant; but if you inquire whether they are beautiful souls, and whether their own acts are like fair pictures, you learn that they are selfish and sensual. Their cultivation is local, as if you should rub a log of dry wood in one spot to produce fire, all the rest remaining cold. Their knowledge of the fine arts is some study of rules and particulars, or some limited judgment of color or form, which is exercised for amusement or for show. It is a proof of the shallowness of the doctrine of beauty as it lies in the minds of our amateurs, that men seem to have lost the perception of the instant dependence of form upon soul. There is no doctrine of forms in our philosophy. We were put into our bodies, as fire is put into a pan to be carried about; but there is no accurate adjustment between the spirit and the organ, much less is the latter the germination of the former. So in regard to other forms, the intellectual men do not believe in any essential dependence of the material world on thought and volition. Theologians think it a pretty air-castle to talk of the Spiritual meaning of a ship or a cloud, of a city or a contract, but they prefer to come again to the solid ground of historical evidence; and even the poets are contented with a civil and conformed manner of living, and to write poems from the fancy, at a safe distance from their own experience. But the highest minds of the world have never ceased to explore the double meaning, or shall I say the quadruple or the centuple or much more manifold meaning, of every sensuous fact; Orpheus, Empedocles, Heraclitus, Plato, Plutarch, Dante, Swedenborg, and the masters of sculpture, picture, and poetry. For we are not pans and barrows, nor even porters of the fire and torch-bearers, but children of the fire, made of it, and only the same divinity transmuted and at two or three removes, when we know least about it. And this hidden truth, that the fountains whence all this river of Time and its creatures floweth are intrinsically ideal and beautiful, draws us to the consideration of the nature and functions of the Poet, or the man of Beauty; to the means and materials he uses, and to the general aspect of the art in the present time.

The breadth of the problem is great, for the poet is representative. He stands among partial men for the complete man, and apprises us not of his wealth, but of the common wealth. The young man reveres men of genius, because, to speak truly, they are more himself than he is. They receive of the soul as he also receives, but they more. Nature enhances her beauty, to the eye of loving men, from their belief that the poet is beholding her shows at the same time. He is isolated among his contemporaries by truth and by his art, but with this consolation in his pursuits, that they will draw all men sooner or later. For all men live by truth and stand in need of expression. In love, in art, in avarice, in politics, in labor, in games, we study to utter our painful secret. The man is only half himself, the other half is his expression.

Notwithstanding this necessity to be published, adequate expression is rare. I know not how it is that we need an interpreter, but the great majority of men seem to be minors, who have not yet come into possession of their own, or mutes, who cannot report the conversation they have had with nature. There is no man who does not anticipate a supersensual utility in the sun and stars, earth and water. These stand and wait to render him a peculiar service. But there is some obstruction or some excess of phlegm in our constitution, which does not suffer them to yield the due effect. Too feeble fall the impressions of nature on us to make us artists. Every touch should thrill. Every man should be so much an artist that he could report in conversation what had befallen him. Yet, in our experience, the rays or appulses have sufficient force to arrive at the senses, but not enough to reach the quick and compel the reproduction of themselves in speech. The poet is the person in whom these powers are in balance, the man without impediment, who sees and handles that which others dream of, traverses the whole scale of experience, and is representative of man, in virtue of being the largest power to receive and to impart.

For the Universe has three children, born at one time, which reappear under different names in every system of thought, whether they be called cause, operation, and effect; or, more poetically, Jove, Pluto, Neptune; or, theologically, the Father, the Spirit, and the Son; but which we will call here the Knower, the Doer, and the Sayer. These stand respectively for the love of truth, for the love of good, and for the love of beauty. These three are equal. Each is that which he is essentially, so that he cannot be surmounted or analyzed, and each of these three has the power of the others latent in him, and his own, patent.

The poet is the sayer, the namer, and represents beauty. He is a sovereign, and stands on the centre. For the world is not painted or adorned, but is from the beginning beautiful; and God has not made some beautiful things, but Beauty is the creator of the universe. Therefore the poet is not any permissive potentate, but is emperor in his own right. Criticism is infested with a cant of materialism, which assumes that manual skill and activity is the first merit of all men, and disparages such as say and do not, overlooking the fact that some men, namely poets, are natural sayers, sent into the world to the end of expression, and confounds them with those whose province is action but who quit it to imitate the sayers. But Homer's words are as costly and admirable to Homer as Agamemnon's victories are to Agamemnon. The poet does not wait for the hero or the sage, but, as they act and think primarily, so he writes primarily what will and must be spoken, reckoning the others, though primaries also, yet, in respect to him, secondaries and servants; as sitters or models in the studio of a painter, or as assistants who bring building materials to an architect.

For poetry was all written before time was, and whenever we are so finely organized that we can penetrate into that region where the air is music, we hear those primal warblings and attempt to write them down, but we lose ever and anon a word or a verse and substitute something of our own, and thus miswrite the poem. The men of more delicate ear write down these cadences more faithfully, and these transcripts, though imperfect, become the songs of the nations. For nature is as truly beautiful as it is good, or as it is reasonable, and must as much appear as it must be done, or be known. Words and deeds are quite indifferent modes of the divine energy. Words are also actions, and actions are a kind of words.

The sign and credentials of the poet are that he announces that which no man foretold. He is the true and only doctor; he knows and tells; he is the only teller of news, for he was present and privy to the appearance which he describes. He is a beholder of ideas and an utterer of the necessary and causal. For we do not speak now of men of poetical talents, or of industry and skill in metre, but of the true poet. I took part in a conversation the other day concerning a recent writer of lyrics, a man of subtle mind, whose head appeared to be a music-box of delicate tunes and rhythms, and whose skill and command of language, we could not sufficiently praise. But when the question arose whether he was not only a lyrist but a poet, we were obliged to confess that he is plainly a contemporary, not an eternal man. He does not stand out of our low limitations, like a Chimborazo under the line, running up from the torrid Base through all the climates of the globe, with belts of the herbage of every latitude on its high and mottled sides; but this genius is the landscape-garden of a modern house, adorned with fountains and statues, with well-bred men and women standing and sitting in the walks and terraces. We hear, through all the varied music, the ground-tone of conventional life. Our poets are men of talents who sing, and not the children of music. The argument is secondary, the finish of the verses is primary.

For it is not metres, but a metre-making argument that makes a poem,—a thought so passionate and alive that like the spirit of a plant or an animal it has an architecture of its own, and adorns nature with a new thing. The thought and the form are equal in the order of time, but in the order of genesis the thought is prior to the form. The poet has a new thought; he has a whole new experience to unfold; he will tell us how it was with him, and all men will be the richer in his fortune. For the experience of each new age requires a new confession, and the world seems always waiting for its poet. I remember when I was young how much I was moved one morning by tidings that genius had appeared in a youth who sat near me at table. He had left his work and gone rambling none knew whither, and had written hundreds of lines, but could not tell whether that which was in him was therein told; he could tell nothing but that all was changed,—man, beast, heaven, earth and sea. How gladly we listened! how credulous! Society seemed to be compromised. We sat in the aurora of a sunrise which was to put out all the stars. Boston seemed to be at twice the distance it had the night before, or was much farther than that. Rome,—what was Rome? Plutarch and Shakspeare were in the yellow leaf, and Homer no more should be heard of. It is much to know that poetry has been written this very day, under this very roof, by your side. What! that wonderful spirit has not expired! These stony moments are still sparkling and animated! I had fancied that the oracles were all silent, and nature had spent her fires; and behold! all night, from every pore, these fine auroras have been streaming. Every one has some interest in the advent of the poet, and no one knows how much it may concern him. We know that the secret of the world is profound, but who or what shall be our interpreter, we know not. A mountain ramble, a new style of face, a new person, may put the key into our hands. Of course the value of genius to us is in the veracity of its report. Talent may frolic and juggle; genius realizes and adds. Mankind in good earnest have availed so far in understanding themselves and their work, that the foremost watchman on the peak announces his news. It is the truest word ever spoken, and the phrase will be the fittest, most musical, and the unerring voice of the world for that time.

All that we call sacred history attests that the birth of a poet is the principal event in chronology. Man, never so often deceived, still watches for the arrival of a brother who can hold him steady to a truth until he has made it his own. With what joy I begin to read a poem which I confide in as an inspiration! And now my chains are to be broken; I shall mount above these clouds and opaque airs in which I live,—opaque, though they seem transparent,—and from the heaven of truth I shall see and comprehend my relations. That will reconcile me to life and renovate nature, to see trifles animated by a tendency, and to know what I am doing. Life will no more be a noise; now I shall see men and women, and know the signs by which they may be discerned from fools and satans. This day shall be better than my birthday: then I became an animal; now I am invited into the science of the real. Such is the hope, but the fruition is postponed. Oftener it falls that this winged man, who will carry me into the heaven, whirls me into mists, then leaps and frisks about with me as it were from cloud to cloud, still affirming that he is bound heavenward; and I, being myself a novice, am slow in perceiving that he does not know the way into the heavens, and is merely bent that I should admire his skill to rise like a fowl or a flying fish, a little way from the ground or the water; but the all-piercing, all-feeding, and ocular air of heaven that man shall never inhabit. I tumble down again soon into my old nooks, and lead the life of exaggerations as before, and have lost my faith in the possibility of any guide who can lead me thither where I would be.

But, leaving these victims of vanity, let us, with new hope, observe how nature, by worthier impulses, has ensured the poet's fidelity to his office of announcement and affirming, namely by the beauty of things, which becomes a new and higher beauty when expressed. Nature offers all her creatures to him as a picture-language. Being used as a type, a second wonderful value appears in the object, far better than its old value; as the carpenter's stretched cord, if you hold your ear close enough, is musical in the breeze. "Things more excellent than every image," says Jamblichus, "are expressed through images." Things admit of being used as symbols because nature is a symbol, in the whole, and in every part. Every line we can draw in the sand has expression; and there is no body without its spirit or genius. All form is an effect of character; all condition, of the quality of the life; all harmony, of health; and for this reason a perception of beauty should be sympathetic, or proper only to the good. The beautiful rests on the foundations of the necessary. The soul makes the body, as the wise Spenser teaches:—'''

string_dict = string.split()
print(string_dict)
counter_dict = {}
for _ in string_dict:
    if _ in counter_dict:
        counter_dict[_] = +1
    else:
        counter_dict[_] = 1
print(counter_dict)

for word in string.split():
    print(word[::-1])














